Repository mpickpt/mana, pull requests merged in 2021-12, with the labels that each got.

#36 [MANA-73] Fix Makefile behavior to copy gethostbyname_proxy to bin
  contrib/mpi-proxy-split/Makefile
  contrib/mpi-proxy-split/lower-half/gethostbyname-static/Makefile
Labels: easy or fast review desired

#35 Misc changes
  contrib/mpi-proxy-split/.gitignore
  contrib/mpi-proxy-split/lower-half/.gitignore
  contrib/mpi-proxy-split/lower-half/gethostbyname-static/.gitignore
  contrib/mpi-proxy-split/lower-half/shm_internal.h
  contrib/mpi-proxy-split/lower-half/shmget.c
  contrib/mpi-proxy-split/mpi-wrappers/mpi_cart_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_collective_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_comm_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_group_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_op_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_request_wrappers.cpp
  contrib/mpi-proxy-split/mpi-wrappers/mpi_type_wrappers.cpp
  contrib/mpi-proxy-split/record-replay.h
  contrib/mpi-proxy-split/two-phase-algo.cpp
  include/dmtcp_dlsym.h
  include/virtualidtable.h
  src/dmtcp_dlsym.cpp
  src/dmtcp_restart.cpp
  src/mtcp/mtcp_restart.c
  src/processinfo.cpp
  src/processinfo.h
  src/threadlist.cpp
  util/memory_access_tracker/memory_access_tracker.h
Labels: enhancement

#29 [MANA-59] Implement dynamic memory region allocation for mtcp_restart.c
  src/mtcp/mtcp_restart.c
Labels: mana-on-centos
