Repository mpickpt/mana, pull requests merged in 2022-04, with the labels that each got.

#93 MANA follows --enable-debug
  contrib/mpi-proxy-split/Makefile
  contrib/mpi-proxy-split/Makefile_config.in
  contrib/mpi-proxy-split/lower-half/Makefile
  contrib/mpi-proxy-split/mpi-wrappers/Makefile
  contrib/mpi-proxy-split/mpi-wrappers/fortran_constants.f90
  contrib/mpi-proxy-split/mpi-wrappers/generate-mpi-dummy-wrappers.py
Labels: enhancement

#96 [MANA-95] Add test case to reproduce the infinite loop issue
  contrib/mpi-proxy-split/mpi-wrappers/Makefile
  contrib/mpi-proxy-split/test/Makefile
  contrib/mpi-proxy-split/test/send_recv_loop.c
Labels: bug, enhancement

#99 [MANA-95] Fix: completePendingIrecvs has infinite loop
  contrib/mpi-proxy-split/p2p_drain_send_recv.cpp
Labels: bug

#103 Fix `gdb-dmtcp-utils` doesn't work with core when getpid() == 1
  util/gdb-dmtcp-utils
Labels: bug

#50 Compilable on gerty
  contrib/mpi-proxy-split/Makefile_config.in
  contrib/mpi-proxy-split/lower-half/Makefile
  contrib/mpi-proxy-split/test-ckpt-restart/Makefile
  contrib/mpi-proxy-split/unit-test/Makefile
  src/mtcp/Makefile.in
Labels: enhancement

#105 Fix RestoreInfo defines differently when --enable-timing
  restart_plugin/mtcp_restart_plugin.h
Labels: bug
